name: Honeycomb Update Marker
description: Update a Marker in Honeycomb
inputs:
  X-Honeycomb-Team:
    description: The Team API Key for authentication
    required: true
  dataset:
    description: The name of the dataset to create the marker in
    required: true
  markerId:
    description: The identifier of the marker
    required: true
  end:
    description: Whether or not to end the marker
    required: false
  type:
    description: The type of marker
    required: false
  message:
    description: The message to attach to the marker
    required: false
  url:
    description: The target for the marker
    required: false
outputs:
  markerId:
    description: The ID of the new marker
runs:
  using: node12
  main: index.js
runs:
  using: node12
  main: index.js
